[web]
class = ['firefox', 'Tor Browser', 'Chromium']
priority = 'firefox'
prog = 'MOZ_WEBRENDER=1 firefox'
keybind_default_next = ['Mod4+w']
ws = 'web'

[web.firefox]
class = ['firefox']
prog = 'MOZ_X11_EGL=1 MOZ_ACCELERATED=1 MOZ_WEBRENDER=1 firefox'
keybind_spec_subtag = ['f']

[web.tor]
class = ['Tor Browser']
prog = 'tor-browser rutracker.org'
keybind_spec_subtag = ['5']

[vid]
class = ['mpv']
prog = '~/bin/pl rofi 1st_level ~/vid/new'
mpd_shut = 0
keybind_default_next = ['Mod4+b']
ws = 'gfx'

[lutris]
class = ['Wine', 'Lutris']
prog = 'lutris'
keybind_default_next = ['Mod4+Control+e']
ws = 'steam'

[steam]
class = ['Steam']
prog = 'steam'
keybind_default_next = ['Mod4+Shift+e']
ws = 'steam'

[doc]
class = ['Zathura', 'cr3']
keybind_default_next = ['Mod4+o']
ws = 'doc'

[vm]
class = ['spicy']
class_r = ['^[Qq]emu-.*$']
keybind_default_next = ['Mod4+Control+v']
ws = 'vm'

[term]
instance = ['term']
spawn = 'term'
keybind_default_next = ['Mod4+x']
ws = 'term'

[nwim]
instance = ['nwim']
spawn = 'nwim'
keybind_default_next = ['Mod4+1']
ws = 'dev'

[obs]
class = ['obs']
prog = 'obs'
keybind_default_toggle = ['Mod4+Shift+o']
ws = 'obs'

[remote]
class = ['xfreerdp', 'reminna', 'org.remmina.Remmina']
keybind_default_toggle = ['Mod4+Control+5']
ws = 'remote'

[sxiv]
class = ['Sxiv']
prog = "dash -c 'exec find ~/dw/ ~/tmp/shots/ -maxdepth 1 -type d -print0 | xargs -0 ~/bin/sx'"
keybind_default_next = ['Mod4+Control+c']
ws = 'gfx'

[sxiv.wallpaper]
class = ["Sxiv"]
prog = "~/bin/wl --show"
keybind_default_subtag = ['Mod4+Shift+c']

[bitwig]
class = [ "Bitwig Studio",]
prog = "bitwig-studio"
keybind_default_next = ['Mod4+Control+b']
ws = 'sound'
